const BLACK_COLOR = '#282828'
const WHITE_COLOR = '#FFF'
const GRAY_COLOR = '#C6C7CB'
const GRAY_DARK_COLOR = '#757575'
const GRAY_LIGHT_COLOR = '#F3F4F5'
const RED_COLOR = '#ff4b00'
const ORANGE_COLOR = '#FF8700'
const BLUE_COLOR = '#213D64'
const BLUE_MOON = '#E4F0FF'
const BLUE_SKY = '#1A87DD'


const Colors = { WHITE_COLOR, BLACK_COLOR, GRAY_COLOR, GRAY_LIGHT_COLOR, GRAY_DARK_COLOR, RED_COLOR, ORANGE_COLOR, BLUE_COLOR, BLUE_MOON, BLUE_SKY }

export default Colors